export const data1 = [
  {
    OrderID: 1001,
    CustomerName: 'Alice Smith',
    ProductCategory: 'Electronics',
    Product: 'Laptop',
    Region: 'North',
    OrderDate: '2024-01-12',
    Quantity: 2,
    Price: 800,
    TotalSales: 1600,
  },
  {
    OrderID: 1002,
    CustomerName: 'Bob Johnson',
    ProductCategory: 'Furniture',
    Product: 'Chair',
    Region: 'South',
    OrderDate: '2024-02-15',
    Quantity: 4,
    Price: 50,
    TotalSales: 200,
  },
  {
    OrderID: 1003,
    CustomerName: 'Charlie Brown',
    ProductCategory: 'Electronics',
    Product: 'Phone',
    Region: 'East',
    OrderDate: '2024-03-10',
    Quantity: 3,
    Price: 600,
    TotalSales: 1800,
  },
  {
    OrderID: 1004,
    CustomerName: 'Alice Smith',
    ProductCategory: 'Clothing',
    Product: 'Jacket',
    Region: 'West',
    OrderDate: '2024-04-05',
    Quantity: 1,
    Price: 120,
    TotalSales: 120,
  },
  {
    OrderID: 1005,
    CustomerName: 'David Lee',
    ProductCategory: 'Electronics',
    Product: 'Tablet',
    Region: 'North',
    OrderDate: '2024-05-20',
    Quantity: 5,
    Price: 300,
    TotalSales: 1500,
  },
  {
    OrderID: 1006,
    CustomerName: 'Emma Davis',
    ProductCategory: 'Furniture',
    Product: 'Table',
    Region: 'South',
    OrderDate: '2024-06-25',
    Quantity: 2,
    Price: 200,
    TotalSales: 400,
  },
  {
    OrderID: 1007,
    CustomerName: 'Bob Johnson',
    ProductCategory: 'Clothing',
    Product: 'Shoes',
    Region: 'West',
    OrderDate: '2024-07-18',
    Quantity: 2,
    Price: 100,
    TotalSales: 200,
  },
  {
    OrderID: 1008,
    CustomerName: 'Charlie Brown',
    ProductCategory: 'Electronics',
    Product: 'Laptop',
    Region: 'East',
    OrderDate: '2024-08-10',
    Quantity: 1,
    Price: 800,
    TotalSales: 800,
  },
  {
    OrderID: 1009,
    CustomerName: 'David Lee',
    ProductCategory: 'Clothing',
    Product: 'Jacket',
    Region: 'North',
    OrderDate: '2024-09-12',
    Quantity: 3,
    Price: 120,
    TotalSales: 360,
  },
  {
    OrderID: 1010,
    CustomerName: 'Emma Davis',
    ProductCategory: 'Furniture',
    Product: 'Chair',
    Region: 'South',
    OrderDate: '2024-10-14',
    Quantity: 6,
    Price: 50,
    TotalSales: 300,
  },
];

export const data2 = [
  {
    date: '2024-01-01',
    product: 'Widget A',
    region: 'North',
    sales: 1000,
    quantity: 50,
  },
  {
    date: '2024-01-01',
    product: 'Widget B',
    region: 'South',
    sales: 1500,
    quantity: 75,
  },
  {
    date: '2024-01-01',
    product: 'Widget D',
    region: 'North',
    sales: 1300,
    quantity: 70,
  },
  {
    date: '2024-01-02',
    product: 'Widget A',
    region: 'East',
    sales: 1200,
    quantity: 60,
  },
  {
    date: '2024-01-02',
    product: 'Widget A',
    region: 'East',
    sales: 100,
    quantity: 44,
  },
  {
    date: '2024-01-02',
    product: 'Widget C',
    region: 'West',
    sales: 800,
    quantity: 40,
  },
  {
    date: '2024-01-03',
    product: 'Widget B',
    region: 'North',
    sales: 1800,
    quantity: 90,
  },
  {
    date: '2024-01-03',
    product: 'Widget C',
    region: 'South',
    sales: 1100,
    quantity: 55,
  },
  {
    date: '2024-01-04',
    product: 'Widget A',
    region: 'West',
    sales: 1300,
    quantity: 65,
  },
  {
    date: '2024-01-04',
    product: 'Widget B',
    region: 'East',
    sales: 1600,
    quantity: 80,
  },
];
