// /**
//  * Creating a sidebar enables you to:
//  - create an ordered group of docs
//  - render a sidebar for each doc of that group
//  - provide next/previous navigation

//  The sidebars can be generated from the filesystem, or explicitly defined here.

//  Create as many sidebars as you want.
//  */

// // @ts-check

// /** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
// const sidebars = {
//   // By default, Docusaurus generates a sidebar from the docs folder structure
//   tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],

//   // But you can create a sidebar manually
//   /*
//   tutorialSidebar: [
//     'intro',
//     'hello',
//     {
//       type: 'category',
//       label: 'Tutorial',
//       items: ['tutorial-basics/create-a-document'],
//     },
//   ],
//    */
// };

// module.exports = sidebars;

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    'introduction',
    'Why-we-use-pivothead',
    'Installation',

    {
      type: 'category',
      label: 'Tutorials',
      link: {
        type: 'generated-index',
        title: 'PivotHead Tutorials',
        description:
          'Learn the core concepts and see practical examples of how to use PivotHead.',
      },
      items: [
        {
          type: 'category',
          label: 'Core',
          items: [
            'tutorial-basics/core/core-concepts',
            'tutorial-basics/core/api-reference',
            'tutorial-basics/core/examples',
          ],
        },

        'tutorial-basics/web-component',

        {
          type: 'category',
          label: 'Framework Wrappers',
          items: [
            'tutorial-basics/wrappers/react',
            'tutorial-basics/wrappers/vue',
          ],
        },
        'tutorial-basics/troubleshooting',
      ],
    },
    {
      type: 'category',
      label: 'Contribution Guide',
      link: {
        type: 'generated-index',
        title: 'Contribution Guide',
        description:
          'Guides for setting up your development environment and contributing to the PivotHead project.',
      },
      items: [
        'contributors/contributors',
        'contributors/how-to-contribute',
        'contributors/code-of-conduct',
        'contributors/monorepo-setup',
        'contributors/quick-start',
      ],
    },
  ],
};

module.exports = sidebars;
